env:
  global:
  - CC_TEST_REPORTER_ID=705ff985a4346f862fc8e1bf06de67f4e7f54ffa0676b794819cbc97a8926db9
language: ruby
rvm:
- 2.6.3
services:
- postgresql
before_install:
- gem update --system
- gem install bundler
install: gem install rails
notifications:
- false
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle install
- rails db:migrate
- rails test
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  api_key:
    secure: SlmH3PGEudOVfoYf6tP45n+33gzlVpr/6WTztUtOxvErpbrsWL4uLJBqFeWgem/Czj7EP3/opBQiwlfPRWKX8zZ3QSAxbiPL2xcIaQCB/ve9DgkcCUBJl7Dtza5AxMnS/QMOpklBff9J9FWs79vLReYQ/jD/ov/uM+0RoEndXKRH6giTdqH/ivBBoZlEYQIJx/ONDpLnTs8eyhyAK/QOnHsa2jCd4VNQa+S7ONpFWiOSG1llJ8RX+azsd5xHwX/lh43oVfxqMlUpOvAUz493gFE6b8+rnqifyavgh88K7QJgXZ4ph+b46XaIpMzys84yQ/i7XIwJQhNu+RqUFb5kRJuaeodUdzdvxUebHDCSh4rL3nhH+ka3j9QoDn5Teq8oVsS4EDwXuNqs/S/BZAsSIGZC6Q85VWdWT9NwrA+lj0YIuBr5I2HlwiZqRHDK+J/rnLvHy6RZ5KYF/IquXtUSu7+uhOgBHgbm+afPBr4dDzMcB3YUX8P9IjADS0NKC2NNW8ra19afRPIfa8Bs+xY/pXIQLwk8xyFcteySeB8dCOpi2+tx8219VgRWz5cdNbsS/Hn10FFxUt+COdifXUKxSHCTZAvjksDTmVs6rK9VDqfU/vD7y2KDrXQ8LkNcrvxvQPy3C5OfWvs0oTJO5migqxP8F8sr6Sm80OLbgVgzPjQ=
  app:
    master: bolah-sample-app
    staging: bolah-sample-app-staging
  run:
  - sleep 10
  - rails db:migrate
  - rails db:seed
